spring:
  config:
    activate:
      on-profile: dev

  jpa:
    hibernate:
      ddl-auto: create

  datasource:
    driver-class-name: org.h2.Driver
    url: ${H2_URL}
    username: mytly
    password: ${H2_PW}

host:
  name: http://localhost:8080
  path: /api/v1/urls/

